### ISSUE TITLE
Cost 

### ISSUE THREAD

**Issue by ghost** [Mindgreppers/HimachalCodeCamp2016#10]
how much cost it will take.

**Comment by mastersilv3r** [comment]
The total cost per attendee should be within Rs. 15000 for six weeks. For
Himachali students, there are scholarships.

You can read more on the wiki.

**Comment by ghost** [comment]
Thanks, how you will shortlisted the student.

**Comment by mastersilv3r** [comment]
We are sending emails to participants and getting to know each other.

Have you got an email from Freeman yet?

**Comment by ghost** [comment]
i have not got any mail uptonow.

**Comment by mastersilv3r** [comment]
Linked to issue #11

**Comment by mastersilv3r** [comment]
@SajjaRaja can I know your email please? dont see an email by this name on the database of applications.

**Comment by ghost** [comment]
rajasajja1@gmail.com

**Comment by bharatagarwal** [comment]
Hi! I haven't received any mail either. I registered with bharatagarwal at gmail dot com.

**Comment by mastersilv3r** [comment]
The cost will be rs. 15000 for six weeks. Also we will need an advance
deposit from the attendees, for confirmation of their attendance.

You will get an email soon. Thanks for being patient.

**Comment by ghost** [comment]
i haven't received any mail at all

**Comment by mastersilv3r** [comment]
@sajjaraja we haven't received your application it seems. Can you apply
(again) please?

**Comment by ghost** [comment]
ok i have applied again.can u please check once sir.
