### ISSUE TITLE
Start Promotional Campaigns - Facebook, Whatsapp, Twitter etc

### ISSUE THREAD

**Issue by prabhu9484** [Mindgreppers/HimachalCodeCamp2016#15]
I received a request from local friends to send a Whatsapp message summarizing CodeCamp 2016
We will need to use popular Social Media to promote CodeCamp in the student / youth community in Dharamshala

**Comment by rajeshdh** [comment]
I would suggest creating some pictures with summary on them. Pictures catch more attention than text posts and also helpful at places like twitter where we have word limits. 
Are we also creating facebook/twitter accounts for codecamp?
