### ISSUE TITLE
Have not received any conformation mail for the CodeCamp application

### ISSUE THREAD

**Issue by div29** [Mindgreppers/HimachalCodeCamp2016#17]
Hey guys i have applied for the CodeCamp but i have not yet received any conformation mail, so can anyone of you guide me regarding this issue? @prabhu9484  @rajeshdh  @jaagameister  @sucheta92  @yayyme

**Comment by mastersilv3r** [comment]
Hi,
Can you tell us your mail ID please?

**Comment by div29** [comment]
divya.rawal94@gmail.com @mastersilv3r

**Comment by jaagameister** [comment]
Delivery to the following recipient failed permanently:

```
 diyva.rawal94@gmail.com
```

Technical details of permanent failure:
Google tried to deliver your message, but it was rejected by the server for
the recipient domain gmail.com by gmail-smtp-in.l.google.com.
[74.125.205.27].

The error that the other server returned was:
550-5.1.1 The email account that you tried to reach does not exist. Please
try
550-5.1.1 double-checking the recipient's email

**Comment by div29** [comment]
Its "divya" and not "diyva" @jaagameister
