### ISSUE TITLE
Suggest DesignSprints before full-blown development on Projects

### ISSUE THREAD

**Issue by prabhu9484** [Mindgreppers/HimachalCodeCamp2016#18]
Suggest DesignSprints before full-blown development on Projects for the following goals:
1. The projects have solid goals
2. The implementations are well thought out
3. The implementation is efficient
4. The outcomes are more measurable

**Comment by mastersilv3r** [comment]
Makes complete sense.

**Comment by prabhu9484** [comment]
Thanks Ayush - if you would like to have DesignSprints, I would like to volunteer as a Lead
