### ISSUE TITLE
What should we backpack to bring on Code Camp

### ISSUE THREAD

**Issue by Shan009** [Mindgreppers/HimachalCodeCamp2016#20]
Hi , 
Would like to have guidance on what to bring on code camp , like clothing and other essential stuffs 
thanks 
shan

**Comment by mastersilv3r** [comment]
- plate, spoon, bowl, glass (must have)
- water bottle (must have)
- notebook and pen
- sleeping mattress/yoga mat (strongly recommended for yoga and sleeping)
- sleeping bag (strongly recommended)
- warm jacket (recommended)
- wind cheater/warm jacket (strongly recommended)
- torch
- shoes for trekking
- cap/hat for covering the head from sun ( strongly recommended for long exposure to sun in case of treks etc)
- sunglasses (recommended)
- blanket (recommended)
