### ISSUE TITLE
One more last desperate person for the codecamp? 

### ISSUE THREAD

**Issue by nanoharsha** [Mindgreppers/HimachalCodeCamp2016#22]

**Comment by nanoharsha** [comment]
In the photos, I see some space around for another tent, and can surely help in kitchen and with some logistics.  
Been planning for past 2 months organizing 3 farmer conferences with almost zero waste, so can contribute in organizing the event as we get close.

**Comment by mastersilv3r** [comment]
Sorry Sreeharsha

We are one week through the camp already. You are still invited to come for
Hillhacks. You can come a few days earlier too!

Hope to see you soon!

Best,
Ag

**Comment by nanoharsha** [comment]
Thanks for the reply Ayush.
Will register and will be there for the hillhacks event, and will make it a
few days in advance.

Cheers
Sreeharsha

On Fri 8 Apr, 2016, 2:35 PM Ayush Ghai, notifications@github.com wrote:

> Sorry Sreeharsha
> 
> We are one week through the camp already. You are still invited to come for
> Hillhacks. You can come a few days earlier too!
> 
> Hope to see you soon!
> 
> Best,
> Ag
> 
> On Fri, Apr 8, 2016 at 2:05 PM, Sreeharsha notifications@github.com
> wrote:
> 
> > Closed #22
> > https://github.com/Mindgreppers/HimachalCodeCamp2016/issues/22.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/Mindgreppers/HimachalCodeCamp2016/issues/22#event-619763763
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/Mindgreppers/HimachalCodeCamp2016/issues/22#issuecomment-207337834
> 
> ## 

Cheers
Sreeharsha
+919966089839

**Comment by Shan009** [comment]
Hi Sreeharsha
You were interested in last years code camp so I thought you should know , we are having metta camp (mettacamp.in) an evolution of code camp.
