### ISSUE TITLE
get coverage in local newspaper

### ISSUE THREAD

**Issue by mastersilv3r** [Mindgreppers/HimachalCodeCamp2016#4]
Preferably Hindi. Try english also.

**Comment by mastersilv3r** [comment]
Lets get the english press release first.

Thanks Prabhu for joining in as volunteer :)

**Comment by mountainfirefly** [comment]
Once English is approved, get a Hindi translation

**Comment by mastersilv3r** [comment]
yes, freeman and I will freeze the content of the english release. Will translate that to hindi. And then we will get them both published simultaneously.

**Comment by mastersilv3r** [comment]
I haven't checked any newspapers. As far as I got to hear, we didn't get covered in Amar Ujala and Punjab Kesri. We would have gotten covered in at least some of them. Wonder if you guys have seen. 

In any case, the press conference and release is done. There was a good attendance and reporters looked pleased and interested. We can close this issue now I guess.

Thanks a lot Prabhu and everyone else :)
