### ISSUE TITLE
Hash out a suggested project list for participants

### ISSUE THREAD

**Issue by mastersilv3r** [Mindgreppers/HimachalCodeCamp2016#6]
As part of the 2:30 - 4:30 session, we will do projects. Small or big. To practice. To learn. To feel useful.

**Comment by prabhu9484** [comment]
Thanks Ayush for the meeting yesterday - I look forward to working with Freeman and you.
I would like to submit my current project - "Avifauna of Pong" Lake for the Code Camp.
The front-end is basic HTML, Jquery, CSS - participants could learn tables and hover functions.
Participants could add additional functionality, like Ishan Sharma contributed sortable tables.
The back-end is in SPARQL results hard-coded as XHTML - from an advanced developers, we could make this dynamic.
I have a wish-list of features, and would appreciate any help with this:

Public Site - http://prabhu9484.github.io/birds2.html
Public Repository - https://github.com/prabhu9484/prabhu9484.github.io
Project Documentation - https://github.com/prabhu9484/prabhu9484.github.io/wiki/Avifauna-of-Pong-Lake---Project-Plan

**Comment by mountainfirefly** [comment]
That will be a great project Prabhu. I have seen the demo and I love it,
for its potential to capture not just avifauna but any fauna, and for bird
watchers and researchers coming to this area, it is a delightful knowledge
bank.

Can you add it to the wiki on a new 'projects to do' page? You have the
write permission.

Personally, I dont prefer jquery. I am biased towards react and material
ui. But since your project is simple, jquery should also suffice. If you
have already built something using jquery then let's just let it be in
jquery. If not, you can consider opening it up for dev in react (which
pankaj/I) are available to teach/guise on during project session daily.
2:30-4:30. That way a learner learns cutting edge technology. Jquery once
revolutionalised the web, but the web has undergone further revolutions
since then. And jquery is still good for simple stuff. But the moment you
have slight complexity, jquery app may turn brittle.

Just my two cents worth thoughts:)

Thanks again!

**Comment by mastersilv3r** [comment]
Err. Fyi, That was silv3r from pankaj's github account :D

**Comment by abhishekbose87** [comment]
Here's a list of open source projects which might be helpful for people learning javascript. But based on the conversation in this thread, will it be useful if you are going to teach React ?

**accounting.js**
https://github.com/openexchangerates/accounting.js
A lightweight JavaScript library for number, money and currency formatting - fully localisable, zero dependencies.http://openexchangerates.github.io/accounting.js

**Tablesorter plugin**
https://github.com/Mottie/tablesorter

**noty**
https://github.com/needim/noty
noty is a jQuery notification plugin that makes it easy to create alert - success - error - warning - information - confirmation messages as an alternative the standard alert dialog.

**clappr**
https://github.com/clappr/clappr
An extensible media player for the web

**Comment by mastersilv3r** [comment]
Hi Abhishek

We are not 'necessarily' limited to react or even js. If someone picks up a project in
another language, they will also get support from us. But me and Freeman will be focussing on js and java.

The idea is: we learn by making projects, we feel good by accomplishing something meaningful at end of codecamp and then we show off all that we did during six weeks at CodeCamp, Hillhacks or anywhere else we wish to.

See the wiki. I have made edits to the description of projects section.

React is for those who want to make a project in react. Jquery for those
with jquery.

**Comment by mastersilv3r** [comment]
Do you know what all can be done/improved in these projects?

**Comment by mastersilv3r** [comment]
@prabhu9484 thanks for creating the wiki page of projects. I have added entry for LifeMaker. So far we have two entries. 
@abhishekbose87 you can add your projects to the list.

**Comment by mastersilv3r** [comment]
@jaagameister you should add the learning x-prize entry preparation here.

**Comment by mastersilv3r** [comment]
@prabhu9484 @sucheta92  as discussed we will get the rakkar village lab kids, rakkar adults and code campers to join the birds projects as data collectors for birds and plants around Rakkar and neighboring areas. In six weeks, let us see what information we can gather of the flora and fauna of this place.

**Comment by abhishekbose87** [comment]
@mastersilv3r Added only accounting.js library to the wiki from the list so that efforts are more focused. Hope that is ok.

**Comment by mastersilv3r** [comment]
Makes sense Abhishek. Thanks!

**Comment by prabhu9484** [comment]
Dear All,

I would like to extend the web-app in the CodeCamp for the following goals:
1. http://prabhu9484.github.io/birds2.html - calendar could show breeding season
2. http://prabhu9484.github.io/birds3.html - change to include snippet - dbo:abstract OR rdfs:comment
3. http://prabhu9484.github.io/birds2.html - fixed box change on-hover to on-click
4. http://prabhu9484.github.io/birds3.html - cleaner layout with no horizontal scroll
5. Extending the features to include upload of images, tagging, other flora and fauna, hindi content
6. Android app

**Comment by prabhu9484** [comment]
Suggesting a new project - I would like to extend the APIs for the India Biodiversity Portal http://indiabiodiversity.org/

**Comment by prabhu9484** [comment]
Thanks Bharath, Supreet, Shaan009 and Sohail for the valuable feedback:

Design intent
Design strategy
Design methodolgy
Case studies
Reference sites - http://hugolpz.github.io/BirdsOfIndia/ Birds Torrent workflow
