### ISSUE TITLE
Make draft of press release in English, then hindi.

### ISSUE THREAD

**Issue by mastersilv3r** [Mindgreppers/HimachalCodeCamp2016#9]
> Study software development from a small village in Himachal. Scholarships available for select Himachalis.

Technology and internet are essential ingredients of our life today. Withdrawing money from ATM machines, searching information on Google, and meeting friends on Facebook all happen with the help of technology.

Website and mobile application development is a highly regarded skill all across the world. A seasoned professional developer can make a healthy earning sitting at her home or even travelling. All that is needed is the right aptitude, a laptop and working internet connection. The people from villages and towns of India run to cities to get expensive certificates in software development and later they struggle to find jobs. Little do they know that they could be learning, doing jobs and even starting their own software businesses, while staying in their villages and towns, hence benefiting their own place and neighbors.

Being a professional technologist doesn't need any certificate. Nor is there any age bar. All you require is curiosity, a certain aptitude and right experience and guidance at the start of your career. At CodeCamp we are going to give learners guidance and a supportive learning environment to help them towards this goal. During this time they take online classes, work on programming challenges, and work on projects to gain experience and develop a profile. After the program participants can continue to learn and do projects from their homes or at Infinity hackbase in Dharamsala or Jaaga Study in Bangalore thereafter.

"The quality of practical exposure will be better than any software engineering or diploma degree in India, even from the IITs. Since we want to promote technology adoption in Himachal, we are giving scholarships to students from the state. Shortlisted students will get their full expenses covered." says Ayush Ghai, a computer engineer from IIT Kanpur, a tech entrepreneur and member of Infinity hackbase at Ghoomakad, village Rakkar, Dharamsala, HP.

Infinity hackbase and Jaaga Study from Bangalore are hosting a Code Camp from April 4th to May 20th, as a donation based not-for-profit community service. There will be scholarships for select Himachali students. Around 40 learners and experts from IITs and all across India and the world are attending, making, learning and teaching. The application deadline is February 25th.

Along with learning programming fundamentals and contributing to Open Source projects that benefit the society, there will be activities like Yoga, meditation, sports, music, cultural exchange with Rakkar village, to provide a wholesome and enjoyable environment of learning.

For more details and application form, visit http://github.com/mindgreppers/HimachalCodeCamp2016/wiki

You can also send an email to talk.to.us@mindgrep.com or call us on 9882883272.

![infinity](https://cloud.githubusercontent.com/assets/11595254/13243475/1552b6fa-da25-11e5-9963-55be75673328.jpg)

**Comment by prabhu9484** [comment]
The steps for the Press Release are:
1. Prepare the Press Release in Hindi and English
2. Decide on a date to hold a Press Conference in Press Club, Kacheri (preferably Sunday)
3. Collect the contact number of journalists of:

Divya Himachal (Hindi)
Dainik Bhaskar (Hindi)
Himachal Dastak (Hindi)
Dainik Jagran (Hindi)
Punjab Kesari (Hindi)
The Tribune (English)

Contact the journalists and inform them to about the Event and the Press Conference, so that they can cover the same
Go to Press Club and hold the Press Conference
Talk about the Event, answer questions and give the Press Release to the journalists assembled
Snacks and tea arrangement always helps ;)

**Comment by mastersilv3r** [comment]
Prabhu Ji

Can you please arrange for the events and let me know the schedule? I will
prepare the release with those dates in mind. Let's have snacks and tea. It
shouldn't be much of an expense. Eventually the cost should get covered by
codecamp attendees' contributions. For now we will fund it.

Thank you very much for the initiation on this. Very nice overview of what
to do. Let's do it. So please see what dates we can book the press club on.
We will also make connect with hillhacks 2016. Two targets with one arrow.

Next week any day works for me.

Thanks again.

**Comment by rajeshdh** [comment]
Doing a press conference directly might cost a bit higher comparing to the overall impact it will make. I would suggest writing a press-note in English or Hindi and mail it to the newspaper editors. Or copies can be given directly to the city reporters of various newspapers. Every newspaper accepts a press note and publish them if coming from a registered entity. 
A press conference can also we proposed in the press-note. So that reporters come there with an idea about the whole thing and have questions prepared.

**Comment by mastersilv3r** [comment]
Hmm. I am not very experienced with writing press releases. I will put
together a write up in english and hindi. and share here. Let us share that
with someone from press industry who can review it, as per the 'press way'

Let me do it by Tuesday.

**Comment by mastersilv3r** [comment]
I am still working on it. It is proving quite challenging to make a good press release. 

Mohinder and @prabhu9484 have made contacts with journalists who will review and then get it published in different places. 

Target date for publishing is around 18th Feb.

**Comment by mastersilv3r** [comment]
Please review

> Study software development from a small village in Himachal. Scholarships available for select Himachalis.

Technology and internet are essential ingredients of our life today. Withdrawing money from ATM machines, searching information on Google, and meeting friends on Facebook all happen with the help of technology.

Website and mobile application development is a highly regarded skill all across the world. A seasoned professional developer can make a healthy earning sitting at her home or even travelling. All that is needed is the right aptitude, a laptop and working internet connection. The people from villages and towns of India run to cities to get expensive certificates in software development and later they struggle to find jobs. Little do they know that they could be learning, doing jobs and even starting their own software businesses, while staying in their villages and towns, hence benefiting their own place and neighbors.

Being a professional technologist doesn't need any certificate. Nor is there any age bar. All you require is curiosity, a certain aptitude and right experience and guidance at the start of your career. At CodeCamp we are going to give learners guidance and a supportive learning environment to help them towards this goal. During this time they take online classes, work on programming challenges, and work on projects to gain experience and develop a profile. After the program participants can continue to learn and do projects from their homes or at Infinity hackbase in Dharamsala or Jaaga Study in Bangalore thereafter.

"The quality of practical exposure will be better than any software engineering or diploma degree in India, even from the IITs. Since we want to promote technology adoption in Himachal, we are giving scholarships to students from the state. Shortlisted students will get their full expenses covered." says Ayush Ghai, a computer engineer from IIT Kanpur, a tech entrepreneur and member of Infinity hackbase at Ghoomakad, village Rakkar, Dharamsala, HP.

Infinity hackbase and Jaaga Study from Bangalore are hosting a Code Camp from April 4th to May 20th, as a donation based not-for-profit community service. There will be scholarships for select Himachali students. Around 40 learners and experts from IITs and all across India and the world are attending, making, learning and teaching. The application deadline is February 25th.

Along with learning programming fundamentals and contributing to Open Source projects that benefit the society, there will be activities like Yoga, meditation, sports, music, cultural exchange with Rakkar village, to provide a wholesome and enjoyable environment of learning.

For more details and application form, visit http://github.com/mindgreppers/HimachalCodeCamp2016/wiki

You can also send an email to talk.to.us@mindgrep.com or call us on 9882883272.

**Comment by rajeshdh** [comment]
I talked with one of my friend who is district head of Dainik Jagran. He forwarded the matter to local reporter and suggested to add a picture also.

**Comment by mastersilv3r** [comment]
Wow! Thanks Rajesh :)

Do we need a hindi release too for them?

**Comment by rajeshdh** [comment]
That would be great. Just a rough draft is enough, they'll do the required editing.

**Comment by mastersilv3r** [comment]
![infinity](https://cloud.githubusercontent.com/assets/11595254/13219246/c63964aa-d994-11e5-8aaa-d64aa3d85909.jpg)

**Comment by mastersilv3r** [comment]
@rajeshdh @prabhu9484 The press release draft is finalized. Also a pic. Please send it to the reporters you know. 

@prabhu9484 we can also do the press conference next sunday.

**Comment by prabhu9484** [comment]
Many thanks Ayush, Rajesh

Please mail the Press Release in English
I will sit with Vicky and get it translated to Hindi tomorrow.

*So excited

**Comment by mastersilv3r** [comment]
@prabhu9484 you can copy paste this draft and send this to reporters with the photo.

**Comment by prabhu9484** [comment]
Dear Ayush,
The draft is good, suggest following change

The application deadline is March 5th for HP students.
You can also send an email to talk.to.us@mindgrep.com or call us on 9882883272 or 8091245489

**Comment by mastersilv3r** [comment]
Please make these changes. Looks good :)

**Comment by prabhu9484** [comment]
Sent the Press Release / Press Conference mail to 119 journalists in HP / Kangra / Dharamshala area
Press Conference in Press Club, Dharamshala (tentative) 27 February, 2016 Saturday.
Meeting with Press Club Head / Dainik Jaagran Official tomorrow with Ayush.

**Comment by mastersilv3r** [comment]
Awesome!

119 is a bit list. I look forward to the meeting tomorrow.

Great work Prabhu. And thanks to your friend Balram for help.

**Comment by prabhu9484** [comment]
Always a pleasure working with you Ayush !
We met Dainik Jaagran and PR Office, they welcomed the initiative and ensured complete support.
The Press Conference for the same is re-scheduled to 29 February, 2016 Monday at 11:30am in THE KUNAL HOTEL (opposite ICICI Bank), Dharamshala.
Press Conference will be followed by Tea & Snacks.

**Comment by prabhu9484** [comment]
Press Release submitted to key journalists in English. They will do the translation in Hindi.
Press Conference done today - attended by around 15 journalists from various media brands in Himachal.
Will be broadcasted today on ETV Himachal at 4:30pm and 7:30pm
Thanks to Ayush, Vaibhav, Sucheta, Balram, Arvind and friends
